### ISSUE TITLE
Top Down template generates compile time errors

### ISSUE THREAD

**Issue by mfigueirido** [vchelaru/FlatRedBall#781] opened 2022-10-21 10:21 UTC
Create a new project using the new project wizard and select "Standard Top Down".

Run the project and these errors show up:
![imaxe](https://user-images.githubusercontent.com/24922404/197172454-9d50d942-3570-4649-b7af-c6dddfcbc272.png)

After this I tried setting de gluj FileVersion to the latest -that is 27- but it didn't change the outcome. This behaviour is replicated by my own project after upgrading to the latest code and I suspect I need to change the project dependencies because of .NET 6 and Monogame 3.8.1, so I hoped I could see how to update those dependencies by looking at the template.

**Comment by vchelaru** [comment] 2022-10-21 11:17
I am unable to reproduce the error so I will provide whatever information I can here to help diagnose the issue.

The reason this error is happening is because of a new entry to the FlatRedBall ICollidable interface:

![image](https://user-images.githubusercontent.com/729631/197182273-82c7a892-2e26-41bb-b811-1287cd394984.png)

These new members make it easier to track collisions and perform logic in an entity based on what it collided with each frame.

FRB Editor (Glue) should be generating those members based on file version, as shown in this code:

![image](https://user-images.githubusercontent.com/729631/197182809-ea7230fd-47ac-4866-8f7c-01173d606f58.png)

As you have correctly guessed, this code only generates if the file version is greater than `ICollidableHasItemsCollidedAgainst`, which is version **22**. Also, note that the code is also checking if your project is linking source, which I believe it is, so it should pass the condition because of either version or source linking.

At this point I think the next step is to run Glue from source, put a breakpoint on that line of code, and right-click on your Player Entity's code folder in Glue and select to **Re-Generate Code** so that the breakpoint is hit. 

![image](https://user-images.githubusercontent.com/729631/197183948-842c7ee6-fc09-42ba-9653-0fbc66c4e28c.png)

That will help us figure out why this error is happening for you, but not for me.

**Comment by vchelaru** [comment] 2022-10-21 12:17
This was caused by the output directory changing when moving to .NET 6.0. The Glue .exe is now in a new spot, but the old one was being used. When running from source everything worked fine.

**Closed as completed by vchelaru** 2022-10-21 12:17 UTC
