### ISSUE TITLE
Gum should keep lists accurate on visibility state change

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#1000] opened 2023-03-22 01:29 UTC
Gum does not revise layout sometimes in horizontal list instances when the visibility state changes. See steps and gif for details.

Repro:

- Create a horizontal list container in a gum component
- Put two items in the list (mine are sprite instances)
- Make the first item not visible, second item will shift
- Make the first item visible again, second item will not return to its proper place

Gif:
![gum-visible-state-change](https://user-images.githubusercontent.com/711100/226778224-0e7dee69-864c-4e8a-8dae-fa1769fcc722.gif)

**Comment by vchelaru** [comment] 2023-03-22 12:44
Thank you for this, it's a very clean repro! 

I believe the cause is the somewhat-recent performance improvement in Gum to reduce layout calls. It seems that I missed a case where layouts should be called but they aren't. I'm investigating now...

**Comment by vchelaru** [comment] 2023-03-22 12:49
Fixed on Gum commit 4f7be9d15eb6fb0ecba97498f576e23b62d26eb4

**Closed as completed by vchelaru** 2023-03-22 12:49 UTC
Labels: bug, gum
