### ISSUE TITLE
Pressing enter on a gum component name should not remove it from parent

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#219] opened 2021-09-29 17:12 UTC
I'm not sure exactly what is happening but the component seems to disappear from the tree view. Here's the repro steps:

1. Have a custom gum component
2. Have a child component named `TestComponent`
3. In the Name field of `TestComponent` type `UpdatedComponentName`
4. Press enter

Expected behavior: the name of `TestComponent` is changed to `UpdatedComponentName`
Actual behavior: the component is removed from the tree and layout is broken

**Comment by vchelaru** [comment] 2022-01-01 19:28
I assume this is referring to having an instance inside a component, as opposed to **parent** and **child** referring to inheritance. Let me know if that's not true.

**Comment by vchelaru** [comment] 2022-01-21 23:29
I worked with @profexorgeek on this, but could not reproduce it. We don't know what may have caused it. Closing for now.

**Closed as completed by vchelaru** 2022-01-21 23:29 UTC
Labels: bug
