### ISSUE TITLE
FRB Editor auto-restarts after changing the texture linked to a TMX but the texture is not getting refreshed

### ISSUE THREAD

**Issue by mfigueirido** [vchelaru/FlatRedBall#418] opened 2022-02-09 15:30 UTC
1. Run the game with this enabled:
![imaxe](https://user-images.githubusercontent.com/24922404/153232301-b1ab5007-becd-4e47-a43e-ed9d66cd5abf.png)

2. The screen shows up like this:
![imaxe](https://user-images.githubusercontent.com/24922404/153232438-49d506ed-07d1-4242-a387-e8e936f1a53c.png)

3. Make a change to the screen's TMX tileset texture and save it (in this case we paint this red square):
![imaxe](https://user-images.githubusercontent.com/24922404/153232642-29665743-5ed7-4862-bc57-df7330411454.png)

4. FRB auto-reloads but the change is not visible:
![imaxe](https://user-images.githubusercontent.com/24922404/153232726-289f1599-6fc8-4192-8663-0f0e67dca0e5.png)

5. If the game is stopped and started again manually the change shows up:
![imaxe](https://user-images.githubusercontent.com/24922404/153232913-f66c7f73-0839-4e36-82a4-371e4a4c538f.png)

FRB is detecting the change but the texture isn't being refreshed.

**Comment by vchelaru** [comment] 2022-02-13 18:51
This is ultimately caused by a bug with the game using the wrong contentmanager for the screens. This has been fixed in the latest commit here:

db91b948e9c96efd86ce6e891fe18230d8a40af5

This should result in the content being loaded correctly, and that will result in the png being unloaded and reloaded when the screen restarts. 

I'm going to close this issue, but we can re-open it or make a new issue if it still reproduces on @mfigueirido 's project.

**Closed as completed by vchelaru** 2022-02-13 18:51 UTC
Labels: bug, edit mode
