### ISSUE TITLE
[Wildcard files] Renaming a global content folder in Windows Explorer results in broken references

### ISSUE THREAD

**Issue by mfigueirido** [vchelaru/FlatRedBall#1001] opened 2023-03-22 10:53 UTC
Steps:

1. Rename a Wildcard files synced folder in Windows Explorer:
![imaxe](https://user-images.githubusercontent.com/24922404/226880972-4ab0d992-d345-4abc-aba2-7706e2fb0699.png)
![imaxe](https://user-images.githubusercontent.com/24922404/226881201-ed4cc76f-94a3-41d2-8a8a-1109f5969ad5.png)

2. See that Glue shows the renamed folder but didn't add the renamed folder files:
![imaxe](https://user-images.githubusercontent.com/24922404/226881658-bd4a8fb5-9de1-4b59-be77-61e553dc85a0.png)

3. Build the game and see that it didn't remove the old references either:
![imaxe](https://user-images.githubusercontent.com/24922404/226881885-62ea9c8c-f716-4780-99f8-4764243e06ae.png)

**Comment by vchelaru** [comment] 2023-03-22 12:31
Thanks for reporting this! 

![22_06 30 33](https://user-images.githubusercontent.com/729631/226905502-aaa69a47-4a90-4ce1-bf42-0795173de891.gif)

3a83630123f79114fe5238552b885a201116d7f4

**Comment by mfigueirido** [comment] 2023-03-22 15:36
Updated the source and found another issue.

It seems like if there are other folders which contain the name of the old folder it messes those folders. Those folders had a file named "c.png" on them -like the one being renamed- and they were wrongly deleted. I guess you coud test it on my old project.

![imaxe](https://user-images.githubusercontent.com/24922404/226953046-a626a119-107a-413d-81d9-a2f16a6e7497.png)
![imaxe](https://user-images.githubusercontent.com/24922404/226952989-d636ebb8-2bb5-4898-a737-0ec0d0280ef4.png)

Also, in no relation to this new issue, Glue creates a lot of tasks that take a while to finish when the rename is happening. It creates around 40-50.

**Comment by mfigueirido** [comment] 2023-03-22 15:46
I leave here some steps to reproduce the latest issue:

1- In global content create three folders named "TestFolder", "TestFolder2" and "TestFolder3".
2- Create a file named c.png and paste it in all three.
3- If a wildcard was set to add .png files those three folders and files will be included in the project by Glue.
4- Rename "TestFolder" to "TestFolderRenamed".
5- See how the renamed folder was included but the files inside "TestFolder2" and "TestFolder3" were deleted by Glue.

**Comment by vchelaru** [comment] 2023-03-24 00:49
@mfigueirido for this setup, are you including folder paths? 

![image](https://user-images.githubusercontent.com/729631/227396351-7838fac7-0e2e-410c-9a57-eff85585e6dc.png)

If not, then you should get errors in Glue

![image](https://user-images.githubusercontent.com/729631/227396292-a70008bf-0c30-4d72-8cce-9f4324bb21a1.png)

Let me know if you are setting this property to true, so that I can follow along properly.

**Comment by mfigueirido** [comment] 2023-03-24 10:19
Yes, I'm including folders. The setup follows a naming convention and without that, as you say, the project wouldn't build.

**Comment by vchelaru** [comment] 2023-03-24 12:29
For the bug to reproduce, you must have one folder named "TestFolder" and another "TestFolder2". The reason this is happening is the FlatRedBall FileManager IsRelativeTo is considering "TestFolder" as relative to "TestFolder2" because "TestFolder2" .Contains("TestFolder").

This is actually a core bug in the FRB file manager implementation, but it happens to cause a bug on wildcards. It will also cause bugs in other places throughout Glue and the FRB engine so this is a very important fix. I'll have it done soon.

**Comment by vchelaru** [comment] 2023-03-24 12:38
Fixed on this commit.

881287221d469ce5fe5be09fc1d81c200f16834f

**Closed as completed by vchelaru** 2023-03-24 12:38 UTC
Labels: bug
