### ISSUE TITLE
Live Edit copy/paste should behave predictably

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#1046] opened 2023-04-27 18:56 UTC
I don't have great repro on this but here are the specific actions I took to get into a bad state:

1. Fetch latest Masteroid.ship_overhaul_2023 repo/branch
2. Go to Stations>StationModules>TestModule
3. Start copy/pasting the hab stack components, change their position, rotation, and "flipped" state
4. Drag a Girder instance from the treeview over the frame
   - Sometimes this works and drops an instance into the preview, other times it doesn't work and you have to drag it to the treeview instead
5. Resize the girder, rotate, and position it
6. Change the Girder's `CurrentGirderStyleState` to something else
7. Go to a different component and come back to the TestModule component

**Observed problems:**

- When returning to the TestModule component there were sometimes multiple visual copies of an instance, but only one in the treeview
- When returning to the TestModule component, the position and state of some objects wasn't saved
- Dragging components from the treeview into my screen showed a "you can't do this" icon and worked sometimes but not other times. You should be able to drag components from the treeview into the current view 

![glue-copy-paste-fail](https://user-images.githubusercontent.com/711100/234964318-f08c3cbb-a4c2-408a-8e2d-065fa3d9c4de.gif)

**Comment by vchelaru** [comment] 2023-04-28 01:32
I've found a number of problems trying to reproduce this issue. 

The first is that pasted objects would not get positioned correctly because the paste code wasn't considering attachment. This has been fixed.

The second bug, which is outstanding, is that when the paste occurs, the code incorrectly adds 2 instances because it is confused about the container type. It basically thinks that the pasted object has another object internally of the same type. 

I will be able to fix this soon.

**Comment by vchelaru** [comment] 2023-04-28 12:56
I've done more research on the duplicate item bug so I'm going to take notes here as I solve it.

The EntityViewingScreen knows that it has a single entity to create. In its AddToManagers it to does so using the InstanceLogic to create the entity. This is the same code that is used to create an entity instance when a new entity is created during edit mode, and as such it is responsible for re-running all commands that may have affected this new instance (such as adding child instances of HabStack.

This runs the DTO from earlier which was created on copy/paste.

After that is finished, the BeforeScreenCustomInitialize method is raised, which is handled in Game1.Generated.cs, which re-runs all commands.

This is normally okay to do in a regular screen, but it is not okay to do on the EntityViewingScreen because the EntityViewingScreen has already run the DTOs for adding a child HabStack as explained above. re-running all commands causes the same add call to be performed again, resulting in 2 instances of HabStack.

The question is - does this mean that ReRunAllGlueToGameCommands should not ever be run on the EntityViewingScreen?

Vic thinks yes... The entity viewing screen will create its own entity instance and re-run all commands on it, so we can put an if check there.

## Update 1

This issue is linked in FRB source to explain why we don't re-run editor commands on entities in the Entity Screen. This applies if the entity is a newly-created entity, and editor commands are properly run on factory entities. But if the entity was created in generated code when the app ran, then it will not run through factories or dynamic creation so we still need to re-run editor commands on it. Therefore, codegen must be modified to handle this. I will link the commit once that is added for future reference.

**Comment by vchelaru** [comment] 2023-04-28 12:57
Okay @profexorgeek I believe at least 2 of the problems you listed above have been reproduced and fixed. I'm not sure if other errors you were experiencing cascaded from those or not, but after fixing those issues I was unable to reproduce other problems. Can you give it a shot and see what you think? I'll close the issue for now and if there are more problems, please open a new issue with repro steps or gifs. Thanks!

**Closed as completed by vchelaru** 2023-04-28 12:57 UTC
Labels: bug, edit mode
