### ISSUE TITLE
Glue reloads whole project after changing two variable values consecutively

### ISSUE THREAD

**Issue by mfigueirido** [vchelaru/FlatRedBall#523] opened 2022-04-07 15:29 UTC
Stumbled upon this after enabing two checkboxes consecutively in an entity variable tab:
![imaxe](https://user-images.githubusercontent.com/24922404/162235531-1f09558f-3f65-472d-a3c6-7b20e63ecfd8.png)

Suddenly tons of tasks are created and they take an eternity to finish:
![imaxe](https://user-images.githubusercontent.com/24922404/162234589-e92d749d-7e98-450d-9635-2e1a75716e37.png)
![imaxe](https://user-images.githubusercontent.com/24922404/162235709-039c45df-0aba-43f2-9a92-4da436ea4b7e.png)

I guess this is caused by a recent change in the task system because it's something that was working fine until the code was updated today.

Edit: Closed Glue, opened again, tried to reproduce it and it didn't. This will be a hard one.

**Comment by vchelaru** [comment] 2022-04-07 21:30
I've also gotten this to happen, but only once. I'm not sure what makes it reproduce consistently :(

**Comment by mfigueirido** [comment] 2022-04-08 08:18
Me neither. If I get proper repro steps I'll let you know.

**Comment by mfigueirido** [comment] 2022-04-08 14:38
I think I have a consistent way to trigger the bug :)

Just add a polygon to an entity and keep spinning the Rotation Z control for some seconds until the "reloading project" message is shown in the output tab.

![imaxe](https://user-images.githubusercontent.com/24922404/162459496-b03a0303-9a3b-4b9b-babd-ffacad19a6a3.png)

**Comment by vchelaru** [comment] 2022-04-15 04:03
Sorry for the slow response, I'm in a branch working on some big changes for the level editor. I'll get to this soon.

**Comment by mfigueirido** [comment] 2022-04-15 08:12
Thank you. It isn't blocking our work so no worries!

**Comment by vchelaru** [comment] 2022-04-16 17:05
I spent some time on this and could not reproduce the issue. However, I believe the issue may be fixed (or improved) due to some Task improvements which were checked in yesterday along with all the edit-mode changes.

Please note that as I was working with the angle UI I realized a lot of issues including performance problems. I have fixed those. I did not fix them to hide this problem. I spent some time trying to reproduce this problem but I couldn't get it to happen. Only after that did I improve the angle selector performance/behavior.

Please let me know if you are able to reproduce this issue after these fixes are in place.

**Comment by mfigueirido** [comment] 2022-04-20 10:02
Nice. Just got the latest code and everything works fine at the moment. Maybe you would prefer to close this issue and I'll reopen it in case the problem creeps up again. Thanks!

**Closed as completed** 2022-04-20 14:52 UTC
