### ISSUE TITLE
Glue shouldn't generate bad class names for Gum objects

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#181] opened 2021-09-08 16:38 UTC
I did some major refactoring of my Gum component folders. In general this worked pretty well but Glue broke codegen in specific cases:

- If an entity has a Gum instance _and_ that Gum instance is the Gum type as `SourceType` the codegen is broken
- If an entity has a Gum instance _and_ that Gum instance is the FlatRedBall type and specifies a GumRuntime, codegein is **not** broken

Glue crash screenshot:
![image](https://user-images.githubusercontent.com/711100/132549414-95b988e2-ce9a-4fcb-adf1-054425a4e187.png)

Bad codegen screenshot:
![image](https://user-images.githubusercontent.com/711100/132549465-d7f450eb-a0cc-48fc-8410-c36adf5a4cb2.png)

Okay codegen:
![image](https://user-images.githubusercontent.com/711100/132549653-a7842cb6-7d4b-4cba-8692-db615a6c3768.png)

**Comment by vchelaru** [comment] 2021-09-08 17:52
This may be caused by the popup that appears in the first screenshot. That popup was a null reference exception which has been fixed. I'm going to close the issue since I believe the root issue is fixed.

**Closed as completed by vchelaru** 2021-09-08 17:52 UTC
Labels: bug
