### ISSUE TITLE
Gum should not need restart when graphics device is lost

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#412] opened 2022-02-09 00:58 UTC
If the display goes to sleep while Gum is running, it will say something like "The graphics device has been lost, restart the app".

If Gum is able to detect that the graphics device has been lost and show a message, it should automatically recover - regain the graphics device and resume normal rendering.

It's disruptive to work flow to forget where you left off and have to restart.

Note that this issue also affects the animation editor.

**Comment by vchelaru** [comment] 2022-03-12 15:17
Currently the preview window uses XNA + Winforms, which loses the graphics device. There are a few ways to fix this:

1. Update the XNA + winforms to support losing graphical device.
2. Move to XNA + WPF, which may already have this fixed. FRB has a template for this which could be used.
3. Move to Monogame + Winforms https://github.com/craftworkgames/MonoGame.WpfCore

Option 1 is probably the worst of all of these options, as everything is moving away from winforms and XNA. However, fixing this would also fix the AnimationEditor.
Option 2 might be the easiest to do incrementally, since it could be added as a separate tab. It would allow the migration of Winforms-specific code to WPF.
Option 3 is the best long-term solution, but it would require a lot of work which can't be done incrementally. MonoGame assemblies cannot be mixed with XNA assemblies, so the two cannot co-exist. Therefore, a copy of the project would have to be made, and it wouldn't run for a while until everything has been converted over to WPF *and* MonoGame.

As I'm writing this out, I wonder if option 2 is the way to go since it allows the incremental move to WPF.

**Comment by vchelaru** [comment] 2024-09-28 15:48
Closing this issue. This is being tracked here:

https://github.com/vchelaru/Gum/issues/178

**Closed as completed by vchelaru** 2024-09-28 15:48 UTC
Labels: bug, gum, huge, PriorityLow

**Comment by kaltinril** [comment] 2024-11-26 01:40
There is already code in your project that will fixe this.

Steps to reproduce:
1. Open GUM
2. Lock your computer with WINDOWS+L
3. Unlock your computer
4. Graphics device is lost

Steps to fix:
1. Add this line of code at 216, and comment out the rest.
2. `TryHandleDeviceReset(mRenderError);`
3. If you still want a fallback, record if we've tried to reset or not, and then display the PaintUsingSystemDrawing instead.

I tested with above code change and it works fine for me.

Submitting a PR against this old ticket.
