### ISSUE TITLE
Fonts become corrupted after changing screens

### ISSUE THREAD

**Issue by mfigueirido** [vchelaru/FlatRedBall#1326] opened 2024-01-18 16:40 UTC
Fonts look ok at first:
![imaxe](https://github.com/vchelaru/FlatRedBall/assets/24922404/137d966d-e9df-4fda-8b78-c442133dbaa1)

But they become corrupted after loading another screen:
![imaxe](https://github.com/vchelaru/FlatRedBall/assets/24922404/12901d99-4899-4e24-8ba9-c6ba2311b820)

Probably something changed regarding Gum content managers in recent commits and causes this behaviour.

**Comment by mfigueirido** [comment] 2024-01-18 18:05
Vic, in case you want to test this on my project, you can change screens just pressing "B" in front of a door.

**Comment by vchelaru** [comment] 2024-01-20 13:42
This was caused by case sensitive comparisons when loading fonts. The font was being loaded in global content first, then later accessed in a screen. The cases were different internally in FRB due to inconsistent ToLower calls. 

This has been fixed by making all dictionaries case insensitive. This has the added benefit of making content work better on linux and other case sensistive OS's.

497a4d0b9c80ba13b7b9467e1f2f928323b661ed

**Closed as completed by vchelaru** 2024-01-20 13:42 UTC
Labels: bug, gum
