### ISSUE TITLE
Floating points don't work in Glue when regional format is set to anything which uses "," as their floating point divider.

### ISSUE THREAD

**Issue by Freestyle00** [vchelaru/FlatRedBall#202] opened 2021-09-23 17:25 UTC
~~So I tried to scale down a Texture Scale in Glue with GlueView in edit mode while regional format was set to "German (Germany)".
But instead of scaling down this happened
Scale 1:
![ArtyParty_qFTC9Sd5fr](https://user-images.githubusercontent.com/69159664/134554603-5ba7e6f5-5448-4c1e-b193-89e1b6e54905.png)
Scale "0.5":
![ArtyParty_WBj5RWS316](https://user-images.githubusercontent.com/69159664/134554676-241fcd97-0475-455c-8333-1476062ce63c.png)
Scale 5:
![ArtyParty_mfpEKaSgnG](https://user-images.githubusercontent.com/69159664/134554742-2f50783c-0018-4b21-b5c6-77485ddabe56.png)~~

Fixed itself I guess

But the same problems remain in the polygons as seen here:
![devenv_aJOJvUVjdb](https://user-images.githubusercontent.com/69159664/134749092-d7687f31-4f5a-4a6b-aa2d-0073b72caea9.png)

To change to German format to reproduce:
Open settings then click this
![ApplicationFrameHost_INjsZNwbWW](https://user-images.githubusercontent.com/69159664/134557655-ac654e88-fba0-49c5-8f47-5e3c72d50380.png)

then click this
![ApplicationFrameHost_Yi224bogEe](https://user-images.githubusercontent.com/69159664/134557764-f910d151-0eef-4b8e-8e8b-a162fac3c837.png)

Now click this
![ApplicationFrameHost_ghQ8JPr3YR](https://user-images.githubusercontent.com/69159664/134557838-8f50eb93-566a-417e-87a7-b78fa06cffa9.png)
Now install German(Germany)
![ApplicationFrameHost_Da7B8VJeFm](https://user-images.githubusercontent.com/69159664/134557922-08f58d74-0ced-4e73-8080-df8f1f4481b7.png)

Then click this
![ApplicationFrameHost_sMLO895eMD](https://user-images.githubusercontent.com/69159664/134558070-f6e698e2-26a1-415f-ada1-910e23ebd2fd.png)

Then change this to German(Germany
![ApplicationFrameHost_7EJOtKPQfc](https://user-images.githubusercontent.com/69159664/134558200-788a2ce5-7d3b-4e30-af69-48271751323f.png)
)

**Comment by vchelaru** [comment] 2021-09-24 00:18
After switching languages/regions, I typed "0,5" with a comma and it worked fine for me. I could not reproduce the problem. Perhaps we can try on screenshare @Freestyle00 ?

**Comment by vchelaru** [comment] 2021-12-31 18:25
Cannot reproduce so I'm going to close this issue unless it comes up again.

**Closed as completed by vchelaru** 2021-12-31 18:25 UTC
Labels: bug
