### ISSUE TITLE
Importing entities from group export doesn't work with entities inside subfolders

### ISSUE THREAD

**Issue by mfigueirido** [vchelaru/FlatRedBall#276] opened 2021-11-30 18:31 UTC
Steps to reproduce:

1. Create a blank project.
2. Right click on Entities and add a new folder.
3. Add a new entity inside this new folder.
3. Click on "Project->Export Group", select the entity we just created and hit "Ok" to save the file.
4. Create another blank project and click on "Project->Import Group".
5. Select the file we created previously.
6. An error window will apear and the entity will not be imported correctly.
![1](https://user-images.githubusercontent.com/24922404/144106615-19b0f65b-918a-498e-add4-217c9248eb2a.png)
![2](https://user-images.githubusercontent.com/24922404/144106624-eadcd5ee-2051-4d5e-b7d5-4c7090337589.png)
![3](https://user-images.githubusercontent.com/24922404/144106629-d9bdd768-f044-4a75-bea9-99bd3b1871b1.png)

**Comment by vchelaru** [comment] 2021-12-01 14:43
I believe this is fixed in the WpfTreeView branch. I am unable to reproduce it there.

**Closed as completed by vchelaru** 2021-12-01 14:43 UTC
