### ISSUE TITLE
New Object window is tiny [on 200%-DPI screen]

### ISSUE THREAD

**Issue by patridge** [vchelaru/FlatRedBall#84] opened 2021-04-21 13:49 UTC
1. Following [BeefBall tutorial to here](https://flatredball.com/documentation/tutorials/tutorials-beefball/tutorials-beefball-creating-an-entity/)
2. Right clicked **Objects** and selected **Add Object**

![image](https://user-images.githubusercontent.com/713665/115564621-dbf3e680-a275-11eb-8d80-8453708169dc.png)

There are several similar windows that don't seem to be happy at high-DPI, but this one popped up a bit small.

**Comment by patridge** [comment] 2021-04-21 14:29
Oddly, if I drag the window to my 100% DPI screen and back, it's sized appropriately.
![image](https://user-images.githubusercontent.com/713665/115570255-33488580-a27b-11eb-9d13-63e2b4158eaf.png)

**Comment by vchelaru** [comment] 2021-04-23 19:15
@patridge I was unable to reproduce this with my main window. I suspect the reason this is happening is because you have multiple windows and the popup may be created on the 100% window, then getting moved quickly before it can resize. 

On devices with consistent %'s, everything works for me. Going to close this because I really don't know how to fix this.

**Closed by vchelaru** 2021-04-23 19:15 UTC

**Comment by patridge** [comment] 2021-04-23 19:23
Possibly related: I was running into this issue when all my new windows were spawning at the bottom right corner of my high-DPI screen. They ended up where I couldn't find them with a mouse and had to use my hack to recover such windows: Alt+Space, M, <any arrow key>, <move mouse with window attached to cursor>.
