### ISSUE TITLE
F2 rename no longer lets you Control+C the selected text

### ISSUE THREAD

**Issue by mfigueirido** [vchelaru/FlatRedBall#999] opened 2023-03-21 17:52 UTC
![imaxe](https://user-images.githubusercontent.com/24922404/226697520-67488096-cd37-4ecd-aa83-095860b4dcb7.png)

This worked fine before but I can no longer copy+paste the name of stuff after pressing F2... this was super handy to paste names on Tiled properties.

(I'm using that for global content files and folders).

**Comment by vchelaru** [comment] 2023-03-22 12:57
Thanks for reporting this. This was caused by the new feature in FRB which allows plugins to respond to hotkey combinations such as CTRL+Z. Unfortunately I didn't run a check to see if a text box was focused before checking for handling the hotkey combination, so copy was not working.

Fixed on commit 3d3e445fc329a967ba130031ae7bfab3d8659945

**Closed as completed by vchelaru** 2023-03-22 12:57 UTC
Labels: bug
