### ISSUE TITLE
[Gum] Guide lines rendering depend on zoom level

### ISSUE THREAD

**Issue by Arcnor** [vchelaru/FlatRedBall#1233] opened 2023-10-07 15:17 UTC
There is a rendering issue in the editor with "guide lines", although this again is probably not the right name. I don't mean the guides you can create by clicking on the ruler at the sides, but all the dotted lines used for various things in the canvas view. For example, depending on the zoom level the lines that appear to give you distance from your guides to the canvas get rendered randomly or even disappear, probably a rounding error, but again, this depends on the zoom level (which should never happen).

You can see in this example how both the vertical white line appears, doubles and disappears randomly depending on how long the line is vertically, but also how the text itself wobbles up and down. It happens with the first zoom level, but not with the second one I try, and with every other level after that.

![Gum_unfIzUmV3S](https://github.com/vchelaru/FlatRedBall/assets/28616/5582eaf6-b250-48d0-9786-8dc5b877a841)

Another place where this happens is with 9-slice guides, I've found lines disappear depending on your zoom level, but I couldn't reproduce it after messing with my project for a while, sorry about that.

**Comment by Arcnor** [comment] 2023-10-07 16:38
Object handles also seem to be affected by this, you can see how the horizontal/vertical handles are flickering between black/white until I change the zoom level.
![Gum_4MQu0FqFFm](https://github.com/vchelaru/FlatRedBall/assets/28616/2b2e749c-436a-4881-b018-1cf7145022ad)

**Comment by vchelaru** [comment] 2023-10-07 17:47
This seems to be an issue with lines adjusting for pixel perfect drawing. I may turn this off for lines. This reproduces easily with two rectangles, one inside the other at 100% zoom.

![image](https://github.com/vchelaru/FlatRedBall/assets/729631/a8c044cc-b44b-43af-94a5-dc198287316d)

**Comment by vchelaru** [comment] 2023-10-07 19:21
Fixed by removing attempting to fix offsets for lines.

**Closed as completed by vchelaru** 2023-10-07 19:21 UTC
Labels: bug, gum
