### ISSUE TITLE
Gum animations' SubAnimations List should be populated

### ISSUE THREAD

**Issue by profexorgeek** [vchelaru/FlatRedBall#540] opened 2022-04-26 21:59 UTC
Repro:

- Create one or more animations that have a named event in them. In my case, the named event was called "LogoImpact"
- Create a composite animation that just plays the sub animations
- Put a breakpoint somewhere and examine the length of the `SubAnimations` property on the composite animation

Expected behavior: The `SubAnimations` collection should contain the sub animations
Actual behavior: The `SubAnimations` collection is empty

I suspect you simply forgot to write the code to add them to the collection. A "FindAllReferences" on the property shows the initialization and an access loop, but no `Add`s:

![image](https://user-images.githubusercontent.com/711100/165399431-ca4e4690-d380-4b04-b111-07ecf26236bb.png)

**Comment by profexorgeek** [comment] 2022-04-26 22:10
As part of this, I investigated overall behavior of sub animations and named events. These are my findings:

- If you bind to childAnimation's named events, they are correctly raised whether the animation is played directly or as a sub animation in a parent.
- If you bind to childAnimation events via the `SubAnimations` property, it won't work because of this bug: the collection is empty
- If you bind to the parent animation, the child animation events are not bubbled up to the parent

These might be separate cards but to keep the discussion in one thread: my opinion is that these scenarios should Just Work™

1. If a developer binds to named events on a parent animation, those events should be raised if any child animation fires that event
2. If a developer puts 3 named events with the same name on any combination of animations, it will be raised each time the named event is encountered in the animation

**Comment by vchelaru** [comment] 2022-04-28 03:13
I was able to reproduce the bug, but to reproduce the issue, the animated component must reference subanimations that are also on the main component (as opposed to subanimations belonging to an instance inside the component).

Codegen was incorrectly only assigning subanimations if they were owned by another object.

Here's an example of what codegen looks like now.

![image](https://user-images.githubusercontent.com/729631/165668932-b75a7cb4-e496-464b-81fe-0e0554d763a4.png)

This is fixed in this commit:

e8f04524afcc728077ac78923572f55aa7aa5f5b

Regarding the **Just Work** conversation, while it may be convenient to bind to animations of one name and have all subanimations bubble that event up, it does make precise binding impossible if a subanimation happens to have an event named the same as an event at the top level.

Of course you might think "I can fix that, I control the names of the animations", but I'm concerned about complex projects where sub animations may go multiple levels deep. It's also possible in the future that components may reference other components which are either not directly owned by the project, or they are maintained by different team members. Coordinating a rename may be difficult, and in such a situation developers would be glad to have the precision of being able to assign named actions precisely.

I'll close now, but if you feel strongly about this, reopen or create another issue and we can talk about alternatives?

**Closed as completed by vchelaru** 2022-04-28 03:13 UTC
Labels: gum
