### ISSUE TITLE
Checking Adjust Reposition Directions on Add And Remove does not affect initial rectangle creation

### ISSUE THREAD

**Issue by treesgobark** [vchelaru/FlatRedBall#1425] opened 2024-06-17 18:27 UTC

**Comment by vchelaru** [comment] 2024-06-17 18:59
![image](https://github.com/vchelaru/FlatRedBall/assets/729631/6778e487-24a6-424a-a622-ff523480206c)

![image](https://github.com/vchelaru/FlatRedBall/assets/729631/1f3340a0-7085-456d-9bc2-017ece8d9727)

**Comment by vchelaru** [comment] 2024-06-19 12:02
It turns out this bug only reproduced if the TileShapeCollection was using custom shapes 
![image](https://github.com/vchelaru/FlatRedBall/assets/729631/f2d27738-f969-45a2-b0dc-06b17342a02c)

The fix has two parts:
1. Custom shape TMX's should result in the internal TileShapeCollection being cloned.
2. Since the original TileShapeCollection did remove reposition directions when created, we will re-add the reposition directions if the reposition checkbox is unchecked.

Fixed in commit b4c68b9c0dee6f0b2b976356bd3b54f1bd41950f

**Closed as completed by vchelaru** 2024-06-19 12:02 UTC
