### ISSUE TITLE
FlatRedBall - Live Edit Desync for newly added Entities via Quick Actions panel

### ISSUE THREAD

**Issue by djjohnsongeek** [vchelaru/FlatRedBall#1337] opened 2024-01-26 14:29 UTC
Sometimes new entities that have been added to a Screen List (while live editor is off) will not update correctly during a live editor session.

On my machine the following behavior is consistent.

1. Launch the FRB Editor
2. Click a GameScreen's entity list (in the tree view)
3. Click the **"Add a new [Entity Name] to the [EntityListName] List"** button in the Quick Actions panel
NOTE: This desync issue does **NOT** occur when right-clicking the entity list and clicking "Add Object"
4. Launch the game from the FRB Editor (either in play or edit mode, switch to edit mode after launch completes if needed)
5. Move the newly added entity around, notice that in the variables panel the entity's x and y position will not update
6. Switch from edit mode to play mode, the new added entity will jump back to where it started (0,0)
7. Sometimes (I have not gotten to test the consistency of this, but it has happend), if the FRB Editor is closed and reopened, the new entity that was not updating in live edit will no longer be in the list when the FRB Editor is reopened.

**Comment by vchelaru** [comment] 2024-10-26 20:25
I believe this was a bug that has been fixed a while ago when we redid the way variables are communicated between game<->FRB. I could not reproduce this with the latest version, so I'm closing this out.

**Closed as completed by vchelaru** 2024-10-26 20:25 UTC

**Comment by djjohnsongeek** [comment] 2024-10-28 12:28
Good stuff! Man I really need to get back into game dev with FRB at some point.
